W4D5/W4D4_classwork/music_app/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :sessions
  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, only: [:create, :edit, :update, :destroy, :show]

end

W4D5/W4D4_classwork/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  year       :string           not null
#  album_type :string           default("studio"), not null
#

class Album < ApplicationRecord
  ALBUM_TYPES = ['live','studio']
  
  validates :band_id, :title, :year, :album_type, presence: true
  # validates :album_type, inclusion: { in: %w(studio, live) }

  belongs_to :band,
  foreign_key: :band_id,
  class_name: 'Band'

end

W4D5/W4D4_classwork/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  foreign_key: :band_id,
  class_name: 'Album',
  dependent: :destroy

end

W4D5/W4D4_classwork/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#

class User < ApplicationRecord
  validates :password_digest, :email, presence: true
  validates :email, uniqueness: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }


  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user
    return nil unless user.is_password?(password)
    user
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

W4D5/W4D4_classwork/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :login_redirect

  def new
    @bands = Band.all
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: @band.id)
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      redirect_to new_band_album_url(@album.band)
    end
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def edit
    @bands = Band.all
    @album = Album.find_by(id: params[:id])
    @band = @album.band
    render :edit
  end

  def update
    @album= Album.find_by(id: params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      redirect_to edit_album_url
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    band = @album.band
    @album.destroy
    redirect_to band_url(band)
  end
  #
  # def edit
  #   @band = Band.find_by(id: params[:id])
  #   render :edit
  # end
  #
  # def update
  #   @band = Band.find_by(id: params[:id])
  #   if @band.update(band_params)
  #     redirect_to band_url(@band)
  #   else
  #     redirect_to edit_band_url
  #   end
  # end
  #
  # def index
  #   @bands = Band.all
  #   render :index
  # end
  #
  # def destroy
  #   @band = Band.find_by(id: params[:id])
  #   @band.destroy
  #   redirect_to bands_url
  # end

  private

  def album_params
    params.require(:album).permit(:title, :year, :album_type, :band_id)
  end
end

W4D5/W4D4_classwork/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user
  helper_method :logged_in?
  helper_method :login_redirect

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    return nil unless current_user
    true
  end

  def login_redirect
    redirect_to new_sessions_url unless logged_in?
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

W4D5/W4D4_classwork/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :login_redirect, only: [:create, :new, :edit, :update, :destroy]

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      redirect_to new_band_url
    end
  end

  def show
    @band =  Band.find_by(id: params[:id])
    render :show
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      redirect_to edit_band_url
    end
  end

  def index
    @bands = Band.all
    render :index
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

W4D5/W4D4_classwork/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    # debugger
    if user.nil?
      flash.now[:errors] = ["Invalid login credentials"]
      redirect_to new_sessions_url
    else
      login!(user)
      flash[:notice] = ["Success!"]
      redirect_to user_url(user)
    end
  end

  def destroy
    logout!
    redirect_to new_sessions_url
  end


end

W4D5/W4D4_classwork/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      flash[:notice] = 'Success!'
      redirect_to bands_url
    else
      flash.now[:errors] = ["Enter a valid username and password"]
      redirect_to new_user_url
    end
  end

  def index

  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W4D5/W4D4_classwork/music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
  "<input
    type='hidden'
    name='authenticity_token'
    value='#{form_authenticity_token}'>".html_safe
  end
end

W4D5/W4D4_classwork/music_app/app/views/albums/_form.html.erb
<h1><%= action == :edit ? "Edit an existing album" : "Create a new album for #{band.name}" %></h1>

<% if action == :edit %>
  <% action_url = album_url(album)%>
<% else %>
  <% action_url = albums_url %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <%= auth_token %>

  <label for="band">Band</label>
  <select id="band" name="album[band_id]">
    <option disabled <%= album.band_id ? "" : "selected"%>>-- Please Select --</option>
    <% @bands.each do |band| %>
      <option value="<%= band.id %>" <%= album.band.id == band.id ? "selected" : ""%>><%= band.name %></option>
    <% end %>
  </select>

  <label for="album_title">Album title</label>
  <input type="text"
    name="album[title]"
    id="album_title"
    value="<%= album.title %>">
  <br>

  <label for="year">Year</label>
  <input id="year" type="text" name="album[year]" value="<%= album.year %>">

  <% Album::ALBUM_TYPES.each do |opt| %>
    <label>
      <input type="radio" name="album[album_type]" value="<%= album.album_type %>"<%= "checked" if album.album_type == opt %>>
      <%= opt %>
    </label>
  <% end %>

  <input type="submit" value="<%= action == :edit ? 'Update album' : 'Create album' %>">
</form>

W4D5/W4D4_classwork/music_app/app/views/albums/edit.html.erb
<%= render 'form', action: :edit, album: @album, band: @band, bands: @bands %>

W4D5/W4D4_classwork/music_app/app/views/albums/new.html.erb
<%= render 'form', action: :new, album: @album, band: @band, bands: @bands %>

W4D5/W4D4_classwork/music_app/app/views/albums/show.html.erb
<h1>Album: <%= @album.title %></h1>
<p><a href="<%= edit_album_url(@album) %>">Edit album</a></p>
<p>Band name: <a href="<%= band_url(@album.band) %>"><%= @album.band.name %></a></p>
<p>Album year: <%= @album.year %></p>
<p>Recording type: <%= @album.album_type %></p>

<form action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <%= auth_token %>
  <input type="submit" value="destroy_album">
</form>

W4D5/W4D4_classwork/music_app/app/views/bands/_form.html.erb
<h1><%= action == :edit ? "Edit an existing band" : "Create a new band" %></h1>

<% if action == :edit %>
  <% action_url = band_url(band)%>
<% else %>
  <% action_url = bands_url %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <%= auth_token %>
  <label for="band_name">Band Name</label>
  <input type="text"
    name="band[name]"
    id="band_name"
    value="<%= band.name %>">
  <br>

  <input type="submit" value="<%= action == :edit ? 'Update band' : 'Create band' %>">
</form>

W4D5/W4D4_classwork/music_app/app/views/bands/edit.html.erb
<%= render 'form', action: :edit, band: @band %>

W4D5/W4D4_classwork/music_app/app/views/bands/index.html.erb
<h1>All the bands</h1>
<ul>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><%= band.name %> </a></li><br>
  <% end %>
</ul>
<br>
<p><a href="<%= new_band_url %>">Add a new band</a></p>

W4D5/W4D4_classwork/music_app/app/views/bands/new.html.erb
<%= render 'form', action: :new, band: @band %>

W4D5/W4D4_classwork/music_app/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<p><a href="<%= edit_band_url(@band) %>">Edit band</a></p>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <%= auth_token %>
  <input type="submit" value="destroy_band">
</form>

<h2>Albums by <%= @band.name %> </h2>
<ul>
  <% @band.albums.each do |album| %>
    <li><a href="<%= album_url(album) %>"><%= album.title %></a></li>
  <% end %>
</ul>

<h2>Create a new album</h2>
<p><a href="<%= new_band_album_url(@band) %>">Add an album</a></p>

W4D5/W4D4_classwork/music_app/app/views/layouts/_errors.html.erb
<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
  <p><%= error %><br /></p>
  <% end %>
<% end %>

W4D5/W4D4_classwork/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <h1>BrokeCloud</h1>
    <a href=" <%= bands_url %> ">Home</a>
    <% if current_user.nil? %>
      <a href="<%= new_sessions_url %>">Sign in</a>
      <a href="<%= new_user_url %>">Sign up</a>
    <% else %>
      <p>Logged in as <%= current_user.email %></p>
      <form action="<%= sessions_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <%= auth_token %>
        <input type="submit" value="logout">
      </form>
    <% end %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

W4D5/W4D4_classwork/music_app/app/views/users/new.html.erb
<h1>New User</h1>

<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
  <p><%= puts "#{error}" %><br /></p>
  <% end %>
<% end %>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label for="user_email">User Name</label>
  <input type="text"
    name="user[email]"
    id="user_email"
    value="">
  <br>

  <label for="user_password">Password</label>
  <input type="password"
    name="user[password]"
    id="user_password"
    value="">
  <br>

  <label for="create_account">Create Account</label>
  <input type="submit" id="create_account">
</form>

W4D5/W4D4_classwork/music_app/app/views/users/show.html.erb
<h1>User page for <%= @user.email %></h1>